### ISSUE TITLE
Some minor feedback

### ISSUE THREAD

**Issue by DanTup** [google/arb-editor#2]
@mosuem I had a quick scan through the code and had some feedback:

1. Snippets are defined against the JSON language, so they show up for all JSON files (inc. non-ARB).
  I don't think there's an easy way to define a new language (ARB) in VS Code and have it inherit the functionality from another language. It would be nice to define "ARB" but inherit everything from "JSON" and then use ARB to target snippets etc., however you can supply snippets via a completion provider which would allow you to check the file extension before providing them. I did something similar in Dart-Code so we could conditionally include Flutter snippets only if the current project is a Flutter project (see https://github.com/Dart-Code/Dart-Code/issues/350).
1. I was a little surprised that the extension modified my user settings file (to add an association) without any prompt or action (I cam to add something and saw an unfamiliar entry at the end of the file). I think it could be done instead by using `contributes/configurationDefaults` in `package.json` to avoid modifying the settings ([example of similar in Dart-Code](https://github.com/Dart-Code/Dart-Code/blob/9f2d5c61bf5b278b57c72191062f25e41216aa90/package.json#L1342)).
1. It probably doesn't matter too much for such a small extension, but currently in `activationEvents` is `onStartupFinished` which means the extension always activates. Generally it's better to only activate when it's certain the user needs the extension (for example `onLanguage`, or `onCommand`).. although, since we can't create an ARB language (without losing basic JSON support), `onLanguage:json` might be the best you can do.
1. Repository/bugs field in `package.json` point to https://github.com/mosum/arb-editor (I presume these should be `google`, but if not, is the username still a typo?)
1. I noticed in #1 you're using `jsonc-parser`.. Is the intention to support comments in these files? (I ask because VS Code has a separate "JSON with comments" language, but I'm not sure if it's safe to have comments here if other tools might be reading the files that might not accept them).
  FWIW, I noticed the visitor in that parser is already providing `offset`s which deals with one thing discussed earlier.

**Comment by mosuem** [comment]
1. fixed by #9, all other in #5.
