### ISSUE TITLE
what is the goal of the arb-editor?

### ISSUE THREAD

**Issue by samuelstroschein** [google/arb-editor#25]
I am wondering what this repo is about and whether or not overlaps with my project https://github.com/inlang/inlang exists. A vs code extension is in the works as well. 

Can someone enlighten me?

**Comment by mosuem** [comment]
Hi, the goal is to provide syntax support for editing `arb` files, which are used by Flutter and Dart for storing translation messages. As the strings use the ICU message format inside, they can be relatively complex, which is where this extension can hopefully help.

I do not know whether that overlaps with the goals of your repository - but please let us know!

**Comment by samuelstroschein** [comment]
Hi Mosuem, 

I just tried the VSCode extension. Yes, there is overlap and I think that's lovely! We should probably bundle our resources. 

The inlang VSCode extension is supposed to make working with all kinds of resource files (.arb, .json, .yaml, etc.) easier for developers. But, the inlang project is also supposed to go multiple steps further by also providing an editor for translators, CLI, CI/CD, plugins, etc., and make localization in its entirety easier.

The ARB-Editor VSCode extension seems to provide linting for .arb resources. We have an ongoing discussion on how to develop a pluggable linting API https://github.com/inlang/inlang/discussions/319. It would mean a lot of you can participate in the discussion, given that you are building the arb-editor extension. Last but not least, what do you think about bundling the resources/make inlang ready for .arb files?

**Comment by mosuem** [comment]
That seems like a great goal - but out of scope for this project. Feel free to contribute a PR to this plugin if you need to expose something for it to interact with your project!
