### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by dilane-goune** [google/arb-editor#36]
- Issue Type: `Performance`
- Extension Name: `arb-editor`
- Extension Version: `0.0.8`
- OS Version: `Linux x64 5.17.5-76051705-generic`
- VS Code version: `1.79.0`

The extension becomes unresponsive went I add a **placeholder** with **plural** or **select** in an **arb file** and completely freeze till i close and reopen the vs code window.

[Google.arb-editor-unresponsive.cpuprofile.txt](https://github.com/google/arb-editor/files/11710757/Google.arb-editor-unresponsive.cpuprofile.txt)

**Comment by mosuem** [comment]
Thanks for reporting and the log!
