### ISSUE TITLE
Ignore placeholder warning if template-arb-file is set

### ISSUE THREAD

**Issue by LHARISMENDY** [google/arb-editor#43]
## Expected Behavior
I would like to request the addition of a feature that allows developers to ignore 'specific linter rules' during arb analysis like "placeholder".

## Actual Behavior
Currently, there is no way to ignore rules like 'Placeholder X not defined in the message metadata'. My 'template-arb-file' is set to my EN file and I should not need to duplicate my placeholder.

## Specifications
- Version of the linter or code analysis tool: v0.0.11
- Platform: macOS

**Comment by mosuem** [comment]
This is probably even more of a bug than a feature.
