### ISSUE TITLE
Provide a way to ignore specific errors/warnings

### ISSUE THREAD

**Issue by PeterStaev** [google/arb-editor#48]
## Expected Behavior
Have a way for a user to define specific errors/warnings/infos that they want to ignore and not show in the Problems section of vscode. May be via a plugin setting to list IDs of the messages user wants to disable, for example:
```json
{
...
"arbeditor.supressedWarnings": [3, 7] // Disable no metadata for key and placeholder metadata errors
}
```

## Actual Behavior
There is no way for a user to ignore a specific warning that the plugin generates while it validates the ARB file. For example, not defining metadata for key/placeholder. 

## Specifications

- Version: 0.0.12
- Platform: macOS

**Comment by f1mclaren** [comment]
I agree. Seeing hundreds of such warnings is very annoying.
