### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by 0rzech** [google/arb-editor#52]
As of now, there's no official Arb Editor build available on [Open VSX](https://open-vsx.org/). Given that both [Flutter](https://open-vsx.org/extension/Dart-Code/flutter) and [Dart](https://open-vsx.org/extension/Dart-Code/dart-code) extensions are officially available there, it would be great if Arb Editor was too.

Somebody has already [published Arb Editor](https://open-vsx.org/extension/bunthoeun/arb-editor) on Open VSX with version that does not match the one from this repository or from VSCode marketplace, but IMHO it would be best if Google published it officially.

AFAIK, VSCode markeplace ToS forbid using it with other editors.

Instructions on how to publish to Open VSX are [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by mosuem** [comment]
Thanks for making me aware of this!

**Comment by mosuem** [comment]
https://open-vsx.org/extension/Google/arb-editor

**Comment by 0rzech** [comment]
Thank you very much!
