### ISSUE TITLE
Support `isCustomDateFormat`

### ISSUE THREAD

**Issue by kzrnm** [google/arb-editor#56]
```json
{
  "dateFormat": "Date: {date}",
  "@dateFormat": {
    "placeholders": {
      "date": {
        "type": "DateTime",
        "format": "yyyy/MM/dd",
        "isCustomDateFormat": "true",
        "example": "2024/08/01"
      }
    }
  }
}
```

## Expected Behavior

No warnings.

## Actual Behavior

 Warning about `format` and `isCustomDateFormat`.

![image](https://github.com/user-attachments/assets/fc9fd5f6-e609-4b9a-b250-1f6814bc2bef)

## Specifications

- Version: v0.0.13
- Platform: Windows

**Comment by mosuem** [comment]
Sounds like a good extension for the json schema. Feel free to file a PR!
