### ISSUE TITLE
arb-editor.suppressedWarnings doesn't work

### ISSUE THREAD

**Issue by lukepighetti** [google/arb-editor#71]
![Image](https://github.com/user-attachments/assets/a241c132-4dbf-4c53-80ba-5a1ab121d6b5)

**Comment by BuyMyBeard** [comment]
> Nice catch [@antoinepemeja](https://github.com/antoinepemeja). [@lukepighetti](https://github.com/lukepighetti), does this solve your issue?

Worked for me

**Comment by mosuem** [comment]
Closing as solved - please re-open if this doesn't work after all.
