### ISSUE TITLE
mismatched_brackets error for single quote in localized string

### ISSUE THREAD

**Issue by BuyMyBeard** [google/arb-editor#72]
For a localization of the sort:
```"noAccount": "Don't have an account?",```
An error is thrown saying there are unbalanced escape quotes.
```
Error: Unbalanced escape quotes. To escape a single quote ', prefix it with another single quote.
```
This is a new bug that seem to have appeared with 0.2.0

**Comment by BuyMyBeard** [comment]
This also causes `metadata_for_missing_key` error to be thrown even when `mismatched_brackets` is suppressed, if the message contains a standalone singlequote.

**Comment by mosuem** [comment]
Thanks for filing this regression.

**Comment by mosuem** [comment]
@BuyMyBeard @l1h2, I can't reproduce this locally. This warning should always fire by default, unless you have it [turned off](https://github.com/google/arb-editor/blob/main/README.md#customize) in the `l10n.yaml`.

Could you share more about your setup?

**Comment by kzrnm** [comment]
@mosuem The default value of `use-escaping` in i18n is false, but in this extension it is true. I suspect this behavior is a bug.
https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization#escaping-syntax

**Comment by l1h2** [comment]
@mosuem you can check https://github.com/l1h2/patient_tracker if you want to try and reproduce.

But to give more information here is `l10n.yaml` :

```yaml
arb-dir: lib/config/localization
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
```

As for the arb file it can be anything that contains single quotes in the string. Ie.:

```json
{
  "@@locale": "en",
  "emptyForm": "Can't save an empty form",
  "@emptyForm": {
    "description": "Empty Form"
  }
}
```

In version 0.0.13 if works normally, but when updating to the newer version (0.2.0), it shows the error messages:

![Image](https://github.com/user-attachments/assets/4119f988-2d3c-483b-a917-38281ee82d7b)

If you need any more information please let me know.

**Comment by BuyMyBeard** [comment]
There is not much to it. this is my l10n.yaml setup

```
arb-dir: lib/l10n
template-arb-file: cxapp_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: lib/l10n/todo_translations.txt
```

I also have some suppressed warnings temporarily until those are fixed in my .code-workspace:

```
"arb-editor.suppressedWarnings": [       
        "missing_metadata_for_key",
				"mismatched_brackets",
				"metadata_for_missing_key"
    ],
```
