### ISSUE TITLE
Incorrect stringmessage snippet structure

### ISSUE THREAD

**Issue by marc22polo** [google/arb-editor#79]
### Description:
The `stringmessage` snippet currently has an extra closing curly brace } and a comma , at the end of the description field, causing parsing errors in VS Code.

### Expected Behavior:
The snippet should correctly generate the following JSON structure:

``` JSON
"testArbBlock": "test",
"@testArbBlock": {
  "description": "Test arb block"
}
```

### Actual Behavior:
The current snippet generates invalid JSON due to the extra } and ,.

``` JSON
"testArbBlock": "test",
"@testArbBlock": {
   "description": "Test arb block",
   }
},
```

### Steps to Reproduce:

- Install the relevant VS Code extension.
- Trigger the stringmessage snippet.
- Fill in the required fields.
- Observe the generated JSON output.

### Proposed Solution:
Remove the extra } and the comma , from the description field in the snippet's body. The corrected snippet should look like this:

```JSON
"stringmessage": {
   "prefix": "string",
   "body": [
      "\"${1:id}\": \"$2\",",
      "\"@${1:id}\": {",
      "  \"description\": \"${1/([a-z]+)(?=[A-Z])|([A-Z])(?=[A-Z])|([A-Z][a-z]+)(?=$)|([A-Z][a-z]+)|([a-z]+)(?=$)/${1:/capitalize}${1:+ }$2${2:+ }${3:/downcase}${4:/downcase}${4:+ }${5:/downcase}/g}\"",
      "},"
   ],
   "description": "A simple ARB string message"
}
```

**Comment by mosuem** [comment]
Thanks for filing this! Feel free to submit a PR as well ;)

**Comment by marc22polo** [comment]
Thanks for the reply! I've submitted a PR with the proposed solution :)
